require 'nginx-conf'

require_relative '../ruby/docker'
require_relative '../config.rb'



cert_path = '/root/cert.pem'
key_path = '/root/key.pem'
socket_path = 'unix:/var/run/fcgiwrap.socket'
htpasswd_file = 'htpasswd'
git_dir = '/git'

conf = nginx_conf do
  http do
    include 'mime.types'

    server do
      listen 443, :ssl

      ssl_certificate     cert_path
      ssl_certificate_key key_path

      location '/' do
        auth_basic "\"Restricted\""
        auth_basic_user_file htpasswd_file

        include 'fastcgi_params'
        fastcgi_param :SCRIPT_FILENAME, '/usr/lib/git-core/git-http-backend'
        fastcgi_param :GIT_PROJECT_ROOT, git_dir
        fastcgi_param :GIT_HTTP_EXPORT_ALL, '""'
        fastcgi_param :PATH_INFO, '$fastcgi_path_info'
        fastcgi_param :PATH_TRANSLATED, '$document_root$fastcgi_path_info'
        fastcgi_param :REMOTE_USER, '$remote_user'
        fastcgi_pass socket_path
      end
    end
  end
end


File.write 'nginx.conf', conf
copy File.join(__dir__, "../security", htpasswd_file), htpasswd_file


docker_tasks :git, "-p #{GIT_PORT}:443" do
  run 'apt -y install nginx git fcgiwrap'

  copy 'nginx.conf', '/etc/nginx/nginx.conf'
  copy htpasswd_file, "/etc/nginx/#{htpasswd_file}"

  volume git_dir
  expose 443

  cmd "fcgiwrap -s #{socket_path} & nginx"
end
