require 'nginx-conf'

require_relative '../ruby/docker'
require_relative '../config'



cert_path = '/root/cert.pem'
key_path = '/root/key.pem'

conf = nginx_conf do
  daemon :off

  events do
  end

  http do
    include 'mime.types'

    server do
      listen 80
      return_ 301, 'https://$host$request_uri'
    end

    server do
      listen 443, :ssl, :http2
      server_name DOMAIN_NAME

      ssl_certificate     cert_path
      ssl_certificate_key key_path

      return_ 301, "https://#{WEB_HOST}$request_uri"
    end

    ssl_server = Proc.new do |host, port|
      server do
        listen 443, :ssl, :http2
        server_name host

        ssl_certificate     cert_path
        ssl_certificate_key key_path

        client_max_body_size POST_MAX_SIZE

        location '/' do
          proxy_pass "https://#{host}:#{port}"
        end
      end
    end

    instance_exec GIT_HOST, GIT_PORT, &ssl_server
    instance_exec WEB_HOST, WEB_PORT, &ssl_server
  end
end


docker_tasks 'nginx-proxy', "-p 443:443 -p 80:80 \
                             -v #{CERT_PATH}:#{cert_path} \
                             -v #{KEY_PATH}:#{key_path}" do
  run 'apt -y update && apt -y upgrade'
  run 'apt -y install nginx'

  File.write 'nginx.conf', conf
  copy 'nginx.conf', '/etc/nginx/nginx.conf'

  expose 80, 443

  cmd :nginx
end
