require_relative '../ruby/docker'


docker_tasks :ubuntu do
  from 'ubuntu:xenial'

  locale = 'en_US.UTF-8'
  run 'locale-gen', locale
  env :LANG, locale
  env :LANGUAGE, locale
  env :LC_ALL, locale

  apt = 'apt -y'
  run apt, :update, '--fix-missing'
  run apt, :upgrade
  onbuild :RUN, apt, :update
  onbuild :RUN, apt, :upgrade
end
