require_relative '../ruby/docker'


docker_tasks :ubuntu do
  from 'ubuntu:xenial'

  en_us = 'en_US.UTF-8'
  run 'locale-gen', en_us
  env :LANG, en_us
  env :LANGUAGE, en_us
  env :LC_ALL, en_us

  apt = 'apt -y'
  run apt, :update, '--fix-missing'
  run apt, :upgrade
  onbuild :RUN, apt, :update
  onbuild :RUN, apt, :upgrade
end
