require_relative '../ruby/docker'


docker_tasks :nsd, '-p 53:53 -p 53:53/udp' do
  run 'apt -y install nsd openssl'

  def in_nsd_dir file
    File.join '/etc/nsd', file
  end

  conf_file = 'nsd.conf'
  zone_file = 'raviqqe.com.zone'

  copy conf_file, in_nsd_dir(conf_file)
  copy zone_file, in_nsd_dir(zone_file)

  expose 53

  cmd 'nsd-control-setup && nsd -d'
end
