require_relative '../ruby/docker'
require_relative '../config'



cert_path = '/root/cert.pem'
key_path = '/root/key.pem'
config_path = '/etc/varnish/default.vcl'


docker_tasks 'varnish', "-p 443:443 -p 80:80 \
                         -v #{CERT_PATH}:#{cert_path} \
                         -v #{KEY_PATH}:#{key_path}" do
  run 'apt -y install varnish'

  # File.write 'varnish.vcl', vcl
  copy 'varnish.vcl', config_path
  run 'chown varnish:varnish', config_path

  expose 80, 443

  cmd [:varnishd, '-a 80', '-a 443', '-F', "-f#{config_path}"]
end
