require 'ini-dsl'

require_relative '../ruby/docker'
require_relative '../config'
require_relative '../security'


home = '/home/git'
gopath = "#{home}/go"
gogs_repo = 'github.com/gogits/gogs'
gogs_dir = "#{gopath}/src/#{gogs_repo}"
cert_path = "#{gogs_dir}/custom/https/fullchain.pem"
key_path = "#{gogs_dir}/custom/https/privkey.pem"

docker_tasks :gogs, %(-p #{GIT_PORT}:#{GIT_PORT} \
                      -e SQL_PASSWORD=#{SQL_PASSWORD} \
                      -v #{CERT_PATH}:#{cert_path} \
                      -v #{KEY_PATH}:#{key_path}) do
  run 'apt -y install golang git'

  run 'adduser --disabled-login --gecos Gogs git'
  user :git


  env :HOME, home
  env :GOPATH, gopath
  env :PATH, '$GOROOT/bin:$GOPATH/bin:$PATH'

  run "go get -u #{gogs_repo}"
  in_gogs_dir = "cd #{gogs_dir} &&"
  run in_gogs_dir, 'go build'

  expose GIT_PORT

  app_ini = ini_file do
    server do
      PROTOCOL :https
      ROOT_URL 'https://' + GIT_HOST
      CERT_FILE cert_path
      KEY_FILE key_path
    end

    repository do
      ROOT "#{home}/repos"
    end

    database do
      PASSWD '`$SQL_PASSWORD`'
    end
  end

  conf_dir = 'custom/conf'

  run in_gogs_dir, "mkdir -p #{conf_dir}"
  cmd in_gogs_dir, \
      "mkdir -p #{conf_dir} && \
       echo #{app_ini.dump.gsub '`', '\\\\`'} > #{conf_dir}/app.ini && \
       ./gogs web --port #{GIT_PORT}"
end
