require_relative '../ruby/docker'
require_relative '../config'


docker_tasks :nsd, "-p #{GIT_PORT}:443" do
  run 'apt -y install golang git'

  run 'adduser --disabled-login --gecos Gogs git'
  user :git

  env :HOME, '/home/git'
  env :GOPATH, '$HOME/go'
  env :PATH, '$GOROOT/bin:$GOPATH/bin:$PATH'

  home = "cd $HOME &&"
  gogs_repo = 'github.com/gogits/gogs'

  run home, "go get -u #{gogs_repo}"
  run "cd $GOPATH/src/#{gogs_repo} && go build"

  expose 443

  cmd 'cd /home/git && gogs web'
end
